# Generated by Django 6.0.3 on 2026-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="driver_license",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="driver_license_state",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
