# Generated by Django 6.0.3 on 2026-03-18 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_profiles", "0002_driverprofile_driver_license_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="driverprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("driver_license__gt", "")),
                fields=("driver_license", "driver_license_state"),
                name="unique_driver_license_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="driverprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("driver_license", ""), ("driver_license_state", "")),
                    models.Q(
                        models.Q(("driver_license", ""), _negated=True),
                        models.Q(("driver_license_state", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="driver_license_both_or_neither",
            ),
        ),
    ]
