# Generated by Django 6.0.3 on 2026-03-17 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'users_customuser') THEN
                            ALTER TABLE users_customuser RENAME TO identity_customuser;
                            ALTER TABLE IF EXISTS users_customuser_groups RENAME TO identity_customuser_groups;
                            ALTER TABLE IF EXISTS users_customuser_user_permissions RENAME TO identity_customuser_user_permissions;
                        ELSIF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'identity_customuser') THEN
                            CREATE TABLE identity_customuser (
                                id BIGSERIAL PRIMARY KEY,
                                password VARCHAR(128) NOT NULL,
                                last_login TIMESTAMPTZ NULL,
                                is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
                                email VARCHAR(254) NOT NULL UNIQUE,
                                is_staff BOOLEAN NOT NULL DEFAULT FALSE,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                date_joined TIMESTAMPTZ NOT NULL
                            );
                            CREATE TABLE identity_customuser_groups (
                                id BIGSERIAL PRIMARY KEY,
                                customuser_id BIGINT NOT NULL REFERENCES identity_customuser(id) DEFERRABLE INITIALLY DEFERRED,
                                group_id INT NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
                                UNIQUE (customuser_id, group_id)
                            );
                            CREATE TABLE identity_customuser_user_permissions (
                                id BIGSERIAL PRIMARY KEY,
                                customuser_id BIGINT NOT NULL REFERENCES identity_customuser(id) DEFERRABLE INITIALLY DEFERRED,
                                permission_id INT NOT NULL REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
                                UNIQUE (customuser_id, permission_id)
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql="ALTER TABLE IF EXISTS identity_customuser RENAME TO users_customuser;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CustomUser",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "password",
                            models.CharField(max_length=128, verbose_name="password"),
                        ),
                        (
                            "last_login",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="last login"
                            ),
                        ),
                        (
                            "is_superuser",
                            models.BooleanField(
                                default=False,
                                help_text="Designates that this user has all permissions without explicitly assigning them.",
                                verbose_name="superuser status",
                            ),
                        ),
                        (
                            "email",
                            models.EmailField(
                                max_length=254,
                                unique=True,
                                verbose_name="email address",
                            ),
                        ),
                        ("is_staff", models.BooleanField(default=False)),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "date_joined",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "groups",
                            models.ManyToManyField(
                                blank=True,
                                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.group",
                                verbose_name="groups",
                            ),
                        ),
                        (
                            "user_permissions",
                            models.ManyToManyField(
                                blank=True,
                                help_text="Specific permissions for this user.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.permission",
                                verbose_name="user permissions",
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                ),
            ],
        ),
    ]
