# Generated by Django 6.0.3 on 2026-03-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name_plural": "Custom Users"},
        ),
    ]
