# Generated by Django 6.0.3 on 2026-03-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_customuser_given_names_customuser_surnames"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="given_names",
            field=models.CharField(max_length=64, verbose_name="given names"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="surnames",
            field=models.CharField(max_length=64, verbose_name="surnames"),
        ),
    ]
