# Generated by Django 6.0.3 on 2026-03-18 04:45
# Originally drivers/0001_initial.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'drivers_driver') THEN
                            ALTER TABLE drivers_driver RENAME TO fleet_driver;
                        ELSIF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'fleet_driver') THEN
                            CREATE TABLE fleet_driver (
                                id BIGSERIAL PRIMARY KEY,
                                created_at TIMESTAMPTZ NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                user_id INTEGER NOT NULL REFERENCES identity_customuser(id) DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql="ALTER TABLE IF EXISTS fleet_driver RENAME TO drivers_driver;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Driver",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
            ],
        ),
    ]
