# Generated by Django 6.0.3 on 2026-03-18 04:45
# Originally vehicles/0001_initial.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'vehicles_vehicle') THEN
                            ALTER TABLE vehicles_vehicle RENAME TO fleet_vehicle;
                        ELSIF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'fleet_vehicle') THEN
                            CREATE TABLE fleet_vehicle (
                                id BIGSERIAL PRIMARY KEY,
                                color VARCHAR(16) NOT NULL,
                                created_at TIMESTAMPTZ NOT NULL,
                                make VARCHAR(32) NOT NULL,
                                model VARCHAR(32) NOT NULL,
                                plate VARCHAR(9) NOT NULL,
                                state VARCHAR(2) NOT NULL,
                                updated_at TIMESTAMPTZ NOT NULL,
                                vin VARCHAR(17) NOT NULL,
                                year INTEGER NOT NULL,
                                user_id BIGINT NOT NULL REFERENCES fleet_driver(id) ON DELETE CASCADE,
                                CONSTRAINT unique_plate_state UNIQUE (plate, state)
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql="ALTER TABLE IF EXISTS fleet_vehicle RENAME TO vehicles_vehicle;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Vehicle",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("color", models.CharField(max_length=16)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("make", models.CharField(max_length=32)),
                        ("model", models.CharField(max_length=32)),
                        ("plate", models.CharField(max_length=9)),
                        ("state", models.CharField(max_length=2)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("vin", models.CharField(max_length=17)),
                        ("year", models.IntegerField()),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="fleet.driver",
                            ),
                        ),
                    ],
                    options={
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("plate", "state"), name="unique_plate_state"
                            )
                        ],
                    },
                ),
            ],
        ),
    ]
