# Generated by Django 6.0.3 on 2026-03-18 04:59
# Originally vehicles/0002_alter_vehicle_options_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_create_vehicle"),
        ("fleet", "0003_add_driver_license_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name_plural": "Vehicles"},
        ),
        migrations.RemoveConstraint(
            model_name="vehicle",
            name="unique_plate_state",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="user",
            new_name="driver_profile",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="license_plate_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("license_plate", "license_plate_state"),
                name="unique_license_plate_state",
            ),
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="plate",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="state",
        ),
    ]
