# Generated by Django 6.0.3 on 2026-03-19 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0006_alter_driver_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="driver_profile",
            new_name="driver",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2011),
                    django.core.validators.MaxValueValidator(2027),
                ]
            ),
        ),
    ]
