# Generated by Django 6.0.3 on 2026-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="given_names",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="surnames",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
