# Generated by Django 6.0.3 on 2026-03-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("make", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=32)),
                ("plate", models.CharField(max_length=9)),
                ("state", models.CharField(max_length=2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vin", models.CharField(max_length=17)),
                ("year", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plate", "state"), name="unique_plate_state"
                    )
                ],
            },
        ),
    ]
