# Generated by Django 6.0.3 on 2026-03-18 23:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_profiles", "0002_driverprofile_driver_license_and_more"),
        ("vehicles", "0002_alter_vehicle_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="vehicle",
            name="unique_license_plate_state",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="driver_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="driver_profiles.driverprofile",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1886),
                    django.core.validators.MaxValueValidator(2027),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("license_plate__gt", "")),
                fields=("license_plate", "license_plate_state"),
                name="unique_license_plate_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("license_plate", ""), ("license_plate_state", "")),
                    models.Q(
                        models.Q(("license_plate", ""), _negated=True),
                        models.Q(("license_plate_state", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="license_plate_both_or_neither",
            ),
        ),
    ]
