# Generated by Django 6.0.3 on 2026-03-19 05:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0007_rename_vehicle_driver_profile_to_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "online_time",
                    models.DurationField(
                        help_text="Total time logged in on the platform (HH:MM:SS)."
                    ),
                ),
                (
                    "active_time",
                    models.DurationField(
                        help_text="Total time spent on trips (HH:MM:SS). Must not exceed online time."
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base pay earned, in USD.",
                        max_digits=8,
                    ),
                ),
                (
                    "tips",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Tips earned, in USD.",
                        max_digits=8,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_entries",
                        to="fleet.driver",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="activity.platform",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("driver", "platform", "date"),
                        name="unique_driver_platform_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active_time__lte", models.F("online_time"))
                        ),
                        name="active_time_lte_online_time",
                    ),
                ],
            },
        ),
    ]
