# Generated by Django 6.0.3 on 2026-04-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_add_vehicle_to_activity_entry"),
        ("fleet", "0007_rename_vehicle_driver_profile_to_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="MileageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month this entry covers, in YYYY-MM format.",
                        max_length=7,
                    ),
                ),
                (
                    "miles",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total miles driven during the month.",
                        max_digits=8,
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax deduction amount for the miles driven, in USD.",
                        max_digits=8,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mileage_entries",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("driver", "month"), name="unique_driver_month_mileage"
                    )
                ],
            },
        ),
    ]
