# Generated by Django 6.0.3 on 2026-04-09 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_add_mileage_entry"),
        ("fleet", "0007_rename_vehicle_driver_profile_to_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date the expense was incurred.")),
                (
                    "vendor",
                    models.CharField(
                        help_text="Name of the vendor or payee.", max_length=128
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasoline"),
                            ("vehicle_maintenance", "Vehicle Maintenance"),
                            ("parking", "Parking"),
                            ("tolls", "Tolls"),
                            ("car_wash", "Car Wash / Detailing"),
                            ("phone_data", "Phone & Data"),
                            ("insurance", "Insurance"),
                            ("registration", "Registration & Licensing"),
                            ("accessories", "Accessories"),
                            ("other", "Other"),
                        ],
                        help_text="Expense category.",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid, in USD.", max_digits=8
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_entries",
                        to="fleet.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_entries",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
    ]
