from typing import Protocol

from fleet.models import Driver, Vehicle


class IDriverRepository(Protocol):
    def get_by_id(self, driver_id: int) -> Driver: ...
    def get_by_user_id(self, user_id: int) -> Driver: ...
    def save(self, driver: Driver) -> Driver: ...


class IVehicleRepository(Protocol):
    def get_by_id(self, vehicle_id: int) -> Vehicle: ...
    def get_by_driver(self, driver: Driver) -> list[Vehicle]: ...
    def save(self, vehicle: Vehicle) -> Vehicle: ...
